model:
  model_path: forager_lite.tflite
  model_name: forager_lite
  input_shapes:
    - 1,224,224,3
  platform: tflite

parser:
  nodes:
    sequential_1/MobileNetV3Large_1/rescaling_1/mul:
      normalization: none
    sequential_1/dense_1/MatMul: {}

postprocessing:
  meta_arch: classification
  labels: ['deadly', 'edible', 'medicinal', 'plants']
  output_offset: [0.0, 0.0, 0.0, 0.0]
  output_scale: [1.0, 1.0, 1.0, 1.0]
